language: cpp

compiler:
    - clang
    - gcc

env:
    - BT=Release
    - BT=Debug

before_install:
    - sudo add-apt-repository ppa:kzemek/boost
    - sudo apt-get -y update -qq

install:
    - curl -sL -o cmake.sh https://cmake.org/files/v3.5/cmake-3.5.0-rc1-Linux-x86_64.sh
    - sudo sh cmake.sh --prefix=/usr/local --exclude-subdir
    - sudo apt-get -y install boost1.58


script:
    - |
        set -eu
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BT}
        cmake --build build
        cmake -E chdir build ctest -T Test
