language: cpp

env:
    - BT=Release
    - BT=Debug

before_install:
    - sudo add-apt-repository ppa:boost-latest/ppa -y
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -y update -qq

install:
    - curl -sL -o cmake.sh https://cmake.org/files/v3.5/cmake-3.5.0-rc1-Linux-x86_64.sh
    - sudo sh cmake.sh --prefix=/usr/local --exclude-subdir
    - sudo apt-get -y install boost1.54 libsqlite3-dev gcc-4.9 g++-4.9


script:
    - |
        set -eu
        env CXX=g++-4.9 cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BT}
        cmake --build build
        cmake -E chdir build ctest -T Test
