language: cpp
compiler:
    - gcc
    - clang

sudo: required
dist: trusty

env:
    - BT=Release
    - BT=Debug

before_install:
    - sudo apt-get -y update -qq

install:
    - curl -sL -o cmake.sh https://cmake.org/files/v3.5/cmake-3.5.0-rc1-Linux-x86_64.sh
    - sudo sh cmake.sh --prefix=/usr/local --exclude-subdir
    - sudo apt-get -y install boost1.54 libsqlite3-dev


script:
    - |
        set -eu
        cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=${BT}
        cmake --build build
        cmake -E chdir build ctest -T Test
        cmake -E chdir build cpack
        set +u
